projects.py: Do not error on delete if force is True
SUSE/osc-tiny pull request #141
Opened 2023-08-04 02:32 UTC by marcosps

2023-08-07 07:51 UTC, crazyscientist requested changes

2023-08-07 07:51 UTC, crazyscientist commented on osctiny/extensions/projects.py
> +            return True
Hi there,

deletion by force is a feature of the [OBS API](https://api.opensuse.org/apidocs/#/Sources%20-%20Projects/delete_source__project_name_):

> Set to `1` if you want to delete the project even if the repositories of other projects include a path to this project.

Without knowing your use case I would argue, that the deletion of a non-existing project (forcefully or otherwise) warrants to return the objectified error message.

Speaking of error messages: If the status code of the response were 404, your `if` block would not get executed, because `self.osc.request` will raise a `HTTPError`.

Would you like to discuss options?

2023-08-08 04:31 UTC, marcosps commented on osctiny/extensions/projects.py
> +            return True
That's true... my use case is to just ignore if the project doesn't exist when force is specified but forgot about the exception...

I'm already handling the HTTPError in my project, but I was expecting of force argument to ignore non-existent projects... either way, we can drop this patch if you think the library user should take care of it :)

2023-08-08 06:58 UTC, crazyscientist commented on osctiny/extensions/projects.py
> +            return True
Thank you for the description of your use case :slightly_smiling_face: 

Your use case makes sense to me, but I can also imagine that for other use cases, where OBS's force deletion is required, the exact error message might be relevant.

If it's OK with you, I'd suggest to handle the case of non-existing projects in your code instead of the library.

2023-08-21 01:32 UTC, marcosps commented on osctiny/extensions/projects.py
> +            return True
Ok, makes sense. Thanks!

2023-08-21 01:32 UTC, closed without merging